# Batch analysis

The `Batch:` class allows users to analyze the tax liabilities of a batch of filing units under current law and under a tax policy reform. 

## Inputs

The class is initialized with a file path to CSV input -- each column contains data on a different tax information variable (e.g. year, marital status, wages, etc.) and each row represents a different filing unit. A detailed discussion of the inputs is [here](https://github.com/PSLmodels/Tax-Cruncher/blob/master/docs/INPUT_INSTRUCTIONS.md).

In [1]:
# import the Batch class
from taxcrunch.multi_cruncher import Batch

In [3]:
# path to input csv file
path = '../docs/example_input.csv'

# initialize an object of the Batch class
b = Batch(path)

## Outputs

Now, we can create a few tables that will show us a detailed breakdown of each filing unit's tax liabilities.

- The `create_table()` method returns a Pandas DataFrame in which each row is a filing unit and each column is an aspect of its tax burden under current law or policy reform. The `write_output_file()` method writes the table as a CSV file.

- The `create_diff_table()` method returns a difference table, where each column shows the difference between liabilities under current law and under policy reform. The `write_diff_file()` method writes the difference table as a CSV file.

To analyze a policy reform, specify the `reform_file` argument in any of the table-making methods. You may enter the file path to a json reform file, a dictionary, or the URL to a reform in the [Tax-Calculator repository](https://github.com/PSLmodels/Tax-Calculator/tree/master/taxcalc/reforms). Make sure that you reform adheres to Tax-Calculator [standards](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/reforms/REFORMS.md).

In [4]:
# outputs under current law (no reform)
b.create_table()

,ID,Individual Income Tax,Payroll Tax,Wages,AGI,UI in AGI,OASDI in AGI,Itemized Deductions,Taxable Inc,Regular Tax,...,Child care credit,EITC,AMT Taxable Income,AMT Liability,Net Investment Income Tax,Income Tax Before Credits,FICA,Payroll Tax MTR,Income Tax MTR,Combined MTR
0,1.0,23397.147200,21137.96192,160000.0,164500.0,0.0,0.0,0.0,146096.8,27397.1472,...,0.0,0.000000,164500.0,0.0,0.0,27397.1472,21137.96192,0.029,0.2400,0.2690
1,2.0,-5385.396064,7267.50000,47500.0,47800.0,0.0,0.0,0.0,23262.4,2365.9536,...,0.0,1751.349664,47800.0,0.0,0.0,2365.9536,7267.50000,0.153,0.3306,0.4836
2,3.0,10049.408800,10710.00000,70000.0,80000.0,0.0,0.0,0.0,67731.2,10049.4088,...,0.0,0.000000,80000.0,0.0,0.0,10049.4088,10710.00000,0.153,0.2200,0.3730
3,4.0,7538.817600,18819.00000,123000.0,124200.0,0.0,0.0,0.0,99662.4,13538.8176,...,0.0,0.000000,124200.0,0.0,0.0,13538.8176,18819.00000,0.153,0.2200,0.3730
4,5.0,40659.745600,23747.96192,250000.0,251200.0,0.0,0.0,0.0,226662.4,42614.1456,...,0.0,0.000000,251200.0,0.0,45.6,42614.1456,23747.96192,0.038,0.2400,0.2780
5,6.0,-530.630000,1683.00000,11000.0,11000.0,0.0,0.0,0.0,0.0,0.0000,...,0.0,530.630000,11000.0,0.0,0.0,0.0000,1683.00000,0.153,0.0000,0.1530
6,7.0,-3402.289388,5967.00000,39000.0,39250.0,0.0,0.0,0.0,20846.8,2193.5232,...,0.0,1595.812588,39250.0,0.0,0.0,2193.5232,5967.00000,0.153,0.3306,0.4836

In [5]:
# outputs under reform
b.create_table(reform_file='../taxcrunch/tests/test_reform.json')

CTC_c was redefined in release 1.0.0

CTC_c was redefined in release 1.0.0

,ID,Individual Income Tax,Payroll Tax,Wages,AGI,UI in AGI,OASDI in AGI,Itemized Deductions,Taxable Inc,Regular Tax,...,Child care credit,EITC,AMT Taxable Income,AMT Liability,Net Investment Income Tax,Income Tax Before Credits,FICA,Payroll Tax MTR,Income Tax MTR,Combined MTR
0,1.0,29979.889250,21137.96192,160000.0,164500.0,0.0,0.0,0.0,141997.51,29039.2814,...,0.0,0.000000,164500.0,940.60785,0.0,29979.88925,21137.96192,0.029,0.3250,0.3540
1,2.0,-3521.399568,7267.50000,47500.0,47800.0,0.0,0.0,0.0,13313.63,1301.3630,...,0.0,1822.762568,47800.0,0.00000,0.0,1301.36300,7267.50000,0.153,0.3106,0.4636
2,3.0,11818.824500,10710.00000,70000.0,80000.0,0.0,0.0,0.0,69115.07,11818.8245,...,0.0,0.000000,80000.0,0.00000,0.0,11818.82450,10710.00000,0.153,0.2500,0.4030
3,4.0,11098.521000,18819.00000,123000.0,124200.0,0.0,0.0,0.0,89713.63,13388.5210,...,0.0,0.000000,124200.0,0.00000,0.0,13388.52100,18819.00000,0.153,0.3000,0.4530
4,5.0,49216.118400,23747.96192,250000.0,251200.0,0.0,0.0,0.0,225191.31,49170.5184,...,0.0,0.000000,251200.0,0.00000,45.6,49170.51840,23747.96192,0.038,0.2800,0.3180
5,6.0,-533.780000,1683.00000,11000.0,11000.0,0.0,0.0,0.0,0.00,0.0000,...,0.0,533.780000,11000.0,0.00000,0.0,0.00000,1683.00000,0.153,0.0000,0.1530
6,7.0,-1878.308196,5967.00000,39000.0,39250.0,0.0,0.0,0.0,16747.51,1776.0025,...,0.0,1654.310696,39250.0,0.00000,0.0,1776.00250,5967.00000,0.153,0.3606,0.5136

In [7]:
b.create_diff_table(reform_file='../taxcrunch/tests/test_reform.json')

CTC_c was redefined in release 1.0.0

CTC_c was redefined in release 1.0.0

,ID,Individual Income Tax Diff,Payroll Tax Diff,Wages Diff,AGI Diff,UI in AGI Diff,OASDI in AGI Diff,Itemized Deductions Diff,Taxable Inc Diff,Regular Tax Diff,...,Child care credit Diff,EITC Diff,AMT Taxable Income Diff,AMT Liability Diff,Net Investment Income Tax Diff,Income Tax Before Credits Diff,FICA Diff,Payroll Tax MTR Diff,Income Tax MTR Diff,Combined MTR Diff
0,1.0,6582.742050,0.0,0.0,0.0,0.0,0.0,0.0,-4099.29,1642.1342,...,0.0,0.000000,0.0,940.60785,0.0,2582.74205,0.0,0.0,0.085,0.085
1,2.0,1863.996496,0.0,0.0,0.0,0.0,0.0,0.0,-9948.77,-1064.5906,...,0.0,71.412904,0.0,0.00000,0.0,-1064.59060,0.0,0.0,-0.020,-0.020
2,3.0,1769.415700,0.0,0.0,0.0,0.0,0.0,0.0,1383.87,1769.4157,...,0.0,0.000000,0.0,0.00000,0.0,1769.41570,0.0,0.0,0.030,0.030
3,4.0,3559.703400,0.0,0.0,0.0,0.0,0.0,0.0,-9948.77,-150.2966,...,0.0,0.000000,0.0,0.00000,0.0,-150.29660,0.0,0.0,0.080,0.080
4,5.0,8556.372800,0.0,0.0,0.0,0.0,0.0,0.0,-1471.09,6556.3728,...,0.0,0.000000,0.0,0.00000,0.0,6556.37280,0.0,0.0,0.040,0.040
5,6.0,-3.150000,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0000,...,0.0,3.150000,0.0,0.00000,0.0,0.00000,0.0,0.0,0.000,0.000
6,7.0,1523.981192,0.0,0.0,0.0,0.0,0.0,0.0,-4099.29,-417.5207,...,0.0,58.498108,0.0,0.00000,0.0,-417.52070,0.0,0.0,0.030,0.030

## Behavioral Responses

Finally, the `Batch` class gives users the option to estimate behavioral responses to a tax policy reform. The three optional arguments for behavioral response analysis are:

- `be_sub`: substitution elasticity of taxable income
- `be_inc`: income elasticity of taxable income
- `be_cg`: semi-elasticity of long-term capital gains

The implementation of these elasticities is carried out by the [Behavioral-Responses](https://github.com/PSLmodels/Behavioral-Responses) project. Further discussion on the definition of the elasticities can be found [here](https://github.com/PSLmodels/Behavioral-Responses/blob/master/behresp/behavior.py)

In [8]:
b.create_table(reform_file='../taxcrunch/tests/test_reform.json', be_sub=0.25)

CTC_c was redefined in release 1.0.0

CTC_c was redefined in release 1.0.0

,ID,Individual Income Tax,Payroll Tax,Wages,AGI,UI in AGI,OASDI in AGI,Itemized Deductions,Taxable Inc,Regular Tax,...,Child care credit,EITC,AMT Taxable Income,AMT Liability,Net Investment Income Tax,Income Tax Before Credits,FICA,Payroll Tax MTR,Income Tax MTR,Combined MTR
0,1.0,28626.460638,21020.498113,155949.523912,160335.604272,0.0,0.0,0.0,137833.114272,27992.784568,...,0.0,0.000000,160335.604272,633.67607,0.0,28626.460638,21020.498113,0.029,0.3250,0.3540
1,2.0,-3460.467696,7297.326357,47694.943511,47996.174733,0.0,0.0,0.0,13509.804733,1320.980473,...,0.0,1781.448169,47996.174733,0.00000,0.0,1320.980473,7297.326357,0.153,0.3106,0.4636
2,3.0,11638.304246,10613.331404,69368.179113,79277.918986,0.0,0.0,0.0,68392.988986,11638.304246,...,0.0,0.000000,79277.918986,0.00000,0.0,11638.304246,10613.331404,0.153,0.2500,0.4030
3,4.0,10248.521858,18389.688839,120194.044702,121366.669528,0.0,0.0,0.0,86880.299528,12680.188382,...,0.0,0.000000,121366.669528,0.00000,0.0,12680.188382,18389.688839,0.153,0.3000,0.4530
4,5.0,48308.801171,23659.138986,246937.140197,248122.438470,0.0,0.0,0.0,222113.748470,48308.801171,...,0.0,0.000000,248122.438470,0.00000,0.0,48308.801171,23659.138986,0.038,0.2800,0.3180
5,6.0,-533.780000,1683.000000,11000.000000,11000.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.0,533.780000,11000.000000,0.00000,0.0,0.000000,1683.000000,0.153,0.0000,0.1530
6,7.0,-1973.400405,5926.910043,38737.974138,38986.294485,0.0,0.0,0.0,16483.804485,1736.446673,...,0.0,1709.847077,38986.294485,0.00000,0.0,1736.446673,5926.910043,0.153,0.3606,0.5136

In [9]:
b.create_diff_table(reform_file='../taxcrunch/tests/test_reform.json', be_sub=0.25)

CTC_c was redefined in release 1.0.0

CTC_c was redefined in release 1.0.0

,ID,Individual Income Tax Diff,Payroll Tax Diff,Wages Diff,AGI Diff,UI in AGI Diff,OASDI in AGI Diff,Itemized Deductions Diff,Taxable Inc Diff,Regular Tax Diff,...,Child care credit Diff,EITC Diff,AMT Taxable Income Diff,AMT Liability Diff,Net Investment Income Tax Diff,Income Tax Before Credits Diff,FICA Diff,Payroll Tax MTR Diff,Income Tax MTR Diff,Combined MTR Diff
0,1.0,5229.313438,-117.463807,-4050.476088,-4164.395728,0.0,0.0,0.0,-8263.685728,595.637368,...,0.0,0.000000,-4164.395728,633.67607,0.0,1229.313438,-117.463807,0.0,0.085,0.085
1,2.0,1924.928368,29.826357,194.943511,196.174733,0.0,0.0,0.0,-9752.595267,-1044.973127,...,0.0,30.098505,196.174733,0.00000,0.0,-1044.973127,29.826357,0.0,-0.020,-0.020
2,3.0,1588.895446,-96.668596,-631.820887,-722.081014,0.0,0.0,0.0,661.788986,1588.895446,...,0.0,0.000000,-722.081014,0.00000,0.0,1588.895446,-96.668596,0.0,0.030,0.030
3,4.0,2709.704258,-429.311161,-2805.955298,-2833.330472,0.0,0.0,0.0,-12782.100472,-858.629218,...,0.0,0.000000,-2833.330472,0.00000,0.0,-858.629218,-429.311161,0.0,0.080,0.080
4,5.0,7649.055571,-88.822934,-3062.859803,-3077.561530,0.0,0.0,0.0,-4548.651530,5694.655571,...,0.0,0.000000,-3077.561530,0.00000,-45.6,5694.655571,-88.822934,0.0,0.040,0.040
5,6.0,-3.150000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.0,3.150000,0.000000,0.00000,0.0,0.000000,0.000000,0.0,0.000,0.000
6,7.0,1428.888983,-40.089957,-262.025862,-263.705515,0.0,0.0,0.0,-4362.995515,-457.076527,...,0.0,114.034489,-263.705515,0.00000,0.0,-457.076527,-40.089957,0.0,0.030,0.030